# For full config options, check the docs:
#    docs.serverless.com

service: merge-chess
# app and org for use with dashboard.serverless.com
#app: merge-chess
#org: theftofaduck

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2
#  stage: dev

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
          Resource: "*" # TODO - Limit this to only the merge-chess tables


# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  patterns:
#    - '!exclude-me.js'
#    - '!exclude-me-dir/**'
#    - include-me.js
#    - include-me-dir/**

functions:
  postStartPublicGame:
    handler: src/endpoints/postStartPublicGame.lambdaHandler
    events:
      - http: # TODO - What's the difference between http and httpApi event types?
          path: api/v1/game/start-public
          method: post

  postStartPrivateGame:
    handler: src/endpoints/postStartPrivateGame.lambdaHandler
    events:
      - http: # TODO - What's the difference between http and httpApi event types?
          path: api/v1/game/start-private
          method: post

  postJoinPrivateGame:
    handler: src/endpoints/postJoinPrivateGame.lambdaHandler
    events:
      - http: # TODO - What's the difference between http and httpApi event types?
          path: api/v1/game/{gameId}/join
          method: post
          request:
            parameters:
              paths:
                gameId: true

  getGameState:
    handler: src/endpoints/getGameState.lambdaHandler
    events:
      - http: # TODO - What's the difference between http and httpApi event types?
          path: api/v1/game/{gameId}/state
          method: get
          request:
            parameters:
              paths:
                gameId: true

  postMove:
    handler: src/endpoints/postMove.lambdaHandler
    events:
      - http: # TODO - What's the difference between http and httpApi event types?
          path: api/v1/game/{gameId}/move
          method: post
          request:
            parameters:
              paths:
                gameId: true

#    Define function environment variables here
#    environment:
#      variable2: value2
# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
